# Generated by Django 4.1.4 on 2023-02-26 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('joining_date', models.DateField()),
                ('department', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('working_desk', models.IntegerField()),
                ('supervisor', models.CharField(max_length=40)),
                ('mobile_no', models.IntegerField()),
                ('email_id', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('resident_address', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('remaining_leaves', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
