# Generated by Django 4.1.4 on 2023-02-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
    ]
