# Generated by Django 4.1.4 on 2023-03-01 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0007_alter_employee_age_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_date', models.DateField()),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateField()),
                ('task', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
