# Generated by Django 4.1.4 on 2023-03-10 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0008_emp_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='remaining_leaves',
            field=models.IntegerField(default=15),
        ),
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('leave_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('leave_type', models.CharField(default='', max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('response', models.CharField(default='', max_length=100)),
                ('leave_from', models.DateField()),
                ('days', models.IntegerField(default=0)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
