# Generated by Django 4.1.4 on 2023-03-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_employee_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_performance',
            name='ending_time',
            field=models.DateTimeField(),
        ),
    ]
