# Generated by Django 4.1.4 on 2023-03-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_leave_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='remaining_leaves',
            field=models.IntegerField(default=15),
        ),
    ]
