# Generated by Django 4.1.4 on 2023-03-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_alter_employee_performance_ending_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_performance',
            old_name='ending_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='employee_performance',
            old_name='starting_time',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='employee_performance',
            name='given_date',
        ),
    ]
