# Generated by Django 3.2 on 2023-03-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_status',
            field=models.CharField(default='Paid', max_length=20),
            preserve_default=False,
        ),
    ]
