# Generated by Django 4.1.4 on 2023-03-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_alter_employee_remaining_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_notes',
            name='leave_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
