# Generated by Django 4.1.4 on 2023-03-06 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_leave_notes_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_notes',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave_notes',
            name='leave_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
