# Generated by Django 3.2 on 2023-03-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_employee_salary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary_status',
            field=models.CharField(default='Unpaid', max_length=20),
        ),
    ]
