# Generated by Django 4.1.4 on 2023-03-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_employee_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_task',
            name='employee_feedback',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee_task',
            name='employee_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee_task',
            name='hr_feedback',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee_task',
            name='hr_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
