# Generated by Django 4.1.4 on 2023-03-02 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0011_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='emp_task',
        ),
    ]
