# Generated by Django 4.1.4 on 2023-03-02 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_employee_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_task',
            name='complete_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
