# Generated by Django 4.1.4 on 2023-03-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_emp_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_task',
            name='time_taken',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.DeleteModel(
            name='Employee_performance',
        ),
    ]
