# Generated by Django 4.1.4 on 2023-03-03 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0011_emp_task_delete_employee_performance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emp_task',
            new_name='e_task',
        ),
    ]
