# Generated by Django 4.1.4 on 2023-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.BigAutoField(default=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
