# Generated by Django 4.1.4 on 2023-03-02 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_alter_employee_task_complete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_task',
            name='complete_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
