# Generated by Django 4.1.4 on 2023-03-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_delete_employee_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='tassssk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
