# Generated by Django 4.1.4 on 2023-03-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_employee_task'),
        ('Employee', '0012_rename_task_emp_task'),
        ('Employee', '0014_tassssk'),
    ]

    operations = [
    ]
