# Generated by Django 4.1.4 on 2023-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0014_alter_employee_task_assigned_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_task',
            name='assigned_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee_task',
            name='complete_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
