# Generated by Django 4.1.4 on 2023-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0015_alter_employee_task_assigned_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_task',
            name='complete_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
