# Generated by Django 4.1.4 on 2023-03-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('vacancy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('main_work', models.CharField(max_length=100)),
                ('salary_range', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('number_of_vacancy', models.IntegerField()),
                ('status', models.CharField(default='Open', max_length=50)),
            ],
        ),
    ]
