# Generated by Django 4.1.4 on 2023-03-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_appliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='requirement',
            field=models.CharField(default='', max_length=200),
        ),
    ]
