# Generated by Django 4.1.4 on 2023-03-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_vacancy_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliers',
            name='cv',
            field=models.FileField(upload_to='Applier/CV'),
        ),
    ]
