# Generated by Django 4.1.4 on 2023-03-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_alter_appliers_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliers',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
