# Generated by Django 3.2 on 2023-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_appliers_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='salaryHistory',
            fields=[
                ('salary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
